"""Tests for AAA generator TRUG detection path."""
from pathlib import Path
from unittest.mock import patch

from trugs_tools.aaa_generator import _compose_aaa, _detect_trug_json


CANONICAL_PATH = (
    Path(__file__).resolve().parents[2]
    / "TRUGS_AAA"
    / "examples"
    / "canonical_example.trug.json"
)


def _canonical_block() -> str:
    return f"```json\n{CANONICAL_PATH.read_text(encoding='utf-8')}\n```"


def test_detect_trug_json_positive():
    body = f"## ARCHITECTURE\n\n{_canonical_block()}"
    parsed = _detect_trug_json(body)
    assert parsed is not None
    assert parsed["type"] == "AAA"


def test_detect_trug_json_negative_non_aaa_json():
    body = """## ARCHITECTURE

```json
{"type":"PROJECT","vocabularies":["aaa_v1"],"nodes":[],"edges":[]}
```
"""
    assert _detect_trug_json(body) is None


def test_detect_trug_json_negative_missing_vocabulary():
    body = """## ARCHITECTURE

```json
{"type":"AAA","capabilities":{"vocabularies":["project_v1"]},"nodes":[],"edges":[]}
```
"""
    assert _detect_trug_json(body) is None


def test_detect_trug_json_ignores_malformed_json_and_finds_later_valid_block():
    body = f"""## ARCHITECTURE

```json
{{"type":"AAA","capabilities":{{"vocabularies":["aaa_v1"]}},}}
```

{_canonical_block()}
"""
    parsed = _detect_trug_json(body)
    assert parsed is not None
    assert parsed["type"] == "AAA"


def test_detect_trug_json_no_json_blocks():
    body = 'markdown mentions "nodes" and "edges" but has no code block'
    assert _detect_trug_json(body) is None


@patch("trugs_tools.aaa_generator._timeline_events", return_value=[])
def test_compose_aaa_uses_trug_renderer_when_detected(mock_timeline):
    issue = {
        "number": 596,
        "title": "Native AAA issue",
        "updated_at": "2026-03-01T00:00:00Z",
        "body": _canonical_block(),
    }
    content = _compose_aaa("TRUGS_AAA", issue, [], "X", "Y")
    assert content.startswith("<!-- GENERATED BY TRUGS — DO NOT EDIT -->")
    assert "**Issue Number:** 596" in content
    assert "## Sub-Issues" not in content


@patch("trugs_tools.aaa_generator._timeline_events", return_value=[])
def test_compose_aaa_markdown_path_unchanged_when_no_trug(mock_timeline):
    issue = {
        "number": 100,
        "title": "Legacy issue",
        "updated_at": "2026-03-01T00:00:00Z",
        "body": "## ARCHITECTURE (Issue TRUG)\nnotes only",
    }
    content = _compose_aaa("TRUGS_TOOLS", issue, [], "X", "Y")
    assert content.startswith("# TRUGS_TOOLS/")
    assert "## ARCHITECTURE\nnotes only" in content
    assert "## Sub-Issues" in content
