"""Tests for twatch and tsync integration commands."""

import json
import pytest
from pathlib import Path

from trugs_tools.filesystem.tinit import tinit
from trugs_tools.filesystem.tadd import tadd
from trugs_tools.filesystem.twatch import twatch
from trugs_tools.filesystem.tsync import tsync
from trugs_tools.filesystem.utils import TRUG_FILENAME, load_graph


# AGENT claude SHALL DEFINE RECORD testtwatch AS A RECORD test_suite.
class TestTwatch:
    # AGENT SHALL VALIDATE PROCESS test_watch_once.
    def test_watch_once(self, tmp_path):
        tinit(tmp_path, name="Test")
        result = twatch(tmp_path, once=True)
        assert isinstance(result, dict)
        assert "AAA.md" in result
        assert "README.md" in result
        assert "ARCHITECTURE.md" in result

    # AGENT SHALL VALIDATE PROCESS test_watch_creates_files.
    def test_watch_creates_files(self, tmp_path):
        tinit(tmp_path, name="Test")
        twatch(tmp_path, once=True)
        assert (tmp_path / "AAA.md").exists()
        assert (tmp_path / "README.md").exists()
        assert (tmp_path / "ARCHITECTURE.md").exists()

    # AGENT SHALL VALIDATE PROCESS test_watch_generated_header.
    def test_watch_generated_header(self, tmp_path):
        tinit(tmp_path, name="Test")
        twatch(tmp_path, once=True)
        aaa = (tmp_path / "AAA.md").read_text()
        assert "GENERATED BY TRUGS" in aaa

    # AGENT SHALL VALIDATE PROCESS test_watch_no_trug.
    def test_watch_no_trug(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            twatch(tmp_path, once=True)

    # AGENT SHALL VALIDATE PROCESS test_watch_callback.
    def test_watch_callback(self, tmp_path):
        tinit(tmp_path, name="Test")
        called = []
        twatch(tmp_path, once=True, callback=lambda r: called.append(r))
        assert len(called) == 1
        assert "AAA.md" in called[0]


# AGENT claude SHALL DEFINE RECORD testtsync AS A RECORD test_suite.
class TestTsync:
    # AGENT SHALL VALIDATE PROCESS test_sync_discovers_new_files.
    def test_sync_discovers_new_files(self, tmp_path):
        tinit(tmp_path, name="Test")
        # Add files after init (not scanned)
        (tmp_path / "new_file.py").write_text("# new")
        (tmp_path / "doc.md").write_text("# doc")

        result = tsync(tmp_path)
        assert "new_file_py" in result["added_nodes"]
        assert "doc_md" in result["added_nodes"]

    # AGENT SHALL VALIDATE PROCESS test_sync_dry_run.
    def test_sync_dry_run(self, tmp_path):
        tinit(tmp_path, name="Test")
        (tmp_path / "new_file.py").write_text("# new")

        result = tsync(tmp_path, dry_run=True)
        assert "new_file_py" in result["added_nodes"]

        # Graph should NOT be modified
        trug = load_graph(tmp_path)
        node_ids = [n["id"] for n in trug["nodes"]]
        assert "new_file_py" not in node_ids

    # AGENT SHALL VALIDATE PROCESS test_sync_detects_removed_files.
    def test_sync_detects_removed_files(self, tmp_path):
        (tmp_path / "keep.py").write_text("# keep")
        (tmp_path / "remove.py").write_text("# remove")
        tinit(tmp_path, name="Test", scan=True)

        # Remove a file
        (tmp_path / "remove.py").unlink()

        result = tsync(tmp_path)
        assert "remove_py" in result["removed_nodes"]

    # AGENT SHALL VALIDATE PROCESS test_sync_ignores_hidden.
    def test_sync_ignores_hidden(self, tmp_path):
        tinit(tmp_path, name="Test")
        (tmp_path / ".hidden").write_text("hidden")
        (tmp_path / "visible.py").write_text("visible")

        result = tsync(tmp_path)
        added = result["added_nodes"]
        assert "visible_py" in added
        # Hidden files should not be added

    # AGENT SHALL VALIDATE PROCESS test_sync_ignores_pycache.
    def test_sync_ignores_pycache(self, tmp_path):
        tinit(tmp_path, name="Test")
        (tmp_path / "__pycache__").mkdir()
        result = tsync(tmp_path)
        added_names = result["added_nodes"]
        assert "__pycache__" not in added_names

    # AGENT SHALL VALIDATE PROCESS test_sync_no_changes.
    def test_sync_no_changes(self, tmp_path):
        tinit(tmp_path, name="Test", scan=True)
        result = tsync(tmp_path)
        assert result["added_nodes"] == []
        assert result["removed_nodes"] == []

    # AGENT SHALL VALIDATE PROCESS test_sync_infers_edges.
    def test_sync_infers_edges(self, tmp_path):
        (tmp_path / "main.py").write_text("import utils\n")
        (tmp_path / "utils.py").write_text("# utils\n")
        tinit(tmp_path, name="Test", scan=True)

        result = tsync(tmp_path, infer_edges=True)
        # Check inferred edges
        edges = result["inferred_edges"]
        ref_edges = [e for e in edges if e["relation"] == "REFERENCES"]
        # main.py imports utils, should create a REFERENCES edge
        has_ref = any(
            e["from_id"] == "main_py" and e["to_id"] == "utils_py"
            for e in ref_edges
        )
        assert has_ref

    # AGENT SHALL VALIDATE PROCESS test_sync_no_infer_edges.
    def test_sync_no_infer_edges(self, tmp_path):
        (tmp_path / "main.py").write_text("import utils\n")
        (tmp_path / "utils.py").write_text("# utils\n")
        tinit(tmp_path, name="Test", scan=True)

        result = tsync(tmp_path, infer_edges=False)
        assert result["inferred_edges"] == []

    # AGENT SHALL VALIDATE PROCESS test_sync_no_trug.
    def test_sync_no_trug(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            tsync(tmp_path)

    # AGENT SHALL VALIDATE PROCESS test_sync_adds_to_root_contains.
    def test_sync_adds_to_root_contains(self, tmp_path):
        tinit(tmp_path, name="Test")
        (tmp_path / "app.py").write_text("# app")

        result = tsync(tmp_path)
        trug = result["trug"]
        root = trug["nodes"][0]
        assert "app_py" in root["contains"]

    # AGENT SHALL VALIDATE PROCESS test_sync_markdown_references.
    def test_sync_markdown_references(self, tmp_path):
        (tmp_path / "README.md").write_text("[guide](GUIDE.md)\n")
        (tmp_path / "GUIDE.md").write_text("# Guide\n")
        tinit(tmp_path, name="Test", scan=True)

        result = tsync(tmp_path, infer_edges=True)
        edges = result["inferred_edges"]
        has_ref = any(
            e["from_id"] == "readme_md" and e["to_id"] == "guide_md"
            for e in edges
        )
        assert has_ref


# AGENT claude SHALL DEFINE RECORD testfilesystemintegration AS A RECORD test_suite.
class TestFilesystemIntegration:
    """End-to-end integration tests for filesystem commands."""

    # AGENT SHALL VALIDATE PROCESS test_init_add_list_workflow.
    def test_init_add_list_workflow(self, tmp_path):
        """Test tinit → tadd → tls workflow."""
        from trugs_tools.filesystem.tls import tls as tls_fn

        # Init
        tinit(tmp_path, name="MyProject")

        # Add files
        (tmp_path / "main.py").write_text("")
        (tmp_path / "lib.py").write_text("")
        tadd(tmp_path, ["main.py", "lib.py"])

        # List
        result = tls_fn(tmp_path, format="json")
        assert len(result) == 2
        names = [item["name"] for item in result]
        assert "main.py" in names
        assert "lib.py" in names

    # AGENT SHALL VALIDATE PROCESS test_init_sync_workflow.
    def test_init_sync_workflow(self, tmp_path):
        """Test tinit → add files → tsync workflow."""
        (tmp_path / "a.py").write_text("")
        tinit(tmp_path, name="Test")

        # Add file after init
        (tmp_path / "b.py").write_text("")
        result = tsync(tmp_path)
        assert "b_py" in result["added_nodes"]
        assert "a_py" in result["added_nodes"]

    # AGENT SHALL VALIDATE PROCESS test_full_workflow.
    def test_full_workflow(self, tmp_path):
        """Test tinit → tadd → tlink → tfind → tmove workflow."""
        from trugs_tools.filesystem.tfind import tfind
        from trugs_tools.filesystem.tmove import tmove
        from trugs_tools.filesystem.tlink import tlink

        # Init and add
        (tmp_path / "src.py").write_text("")
        (tmp_path / "test.py").write_text("")
        tinit(tmp_path, name="App", scan=True)

        # Link
        tlink(tmp_path, "src_py", "test_py", "TESTS")

        # Find
        found = tfind(tmp_path, edge_relation="TESTS", format="json")
        assert any(item["id"] in ("src_py", "test_py") for item in found)

        # Rename
        tmove(tmp_path, "src_py", new_name="app.py")
        trug = load_graph(tmp_path)
        node = [n for n in trug["nodes"] if n["id"] == "src_py"][0]
        assert node["properties"]["name"] == "app.py"
        assert (tmp_path / "app.py").exists()

    # AGENT SHALL VALIDATE PROCESS test_init_watch_workflow.
    def test_init_watch_workflow(self, tmp_path):
        """Test tinit → twatch (once) workflow."""
        tinit(tmp_path, name="WatchTest")
        twatch(tmp_path, once=True)
        assert (tmp_path / "AAA.md").exists()
        assert (tmp_path / "README.md").exists()
        assert (tmp_path / "ARCHITECTURE.md").exists()


# AGENT claude SHALL DEFINE RECORD testhubreadyworkflow AS A RECORD test_suite.
class TestHubReadyWorkflow:
    """Integration test for hub-ready TRUG workflow with weight and qualifying_interest."""

    # AGENT SHALL VALIDATE PROCESS test_create_hub_ready_trug.
    def test_create_hub_ready_trug(self, tmp_path):
        """tinit(qualifying_interest) → tadd → tlink(weight) → validate → render."""
        from trugs_tools.filesystem.tlink import tlink
        from trugs_tools.validator import validate_trug
        from trugs_tools.renderer import render_architecture

        # Create files to add
        (tmp_path / "main.py").write_text("# main")
        (tmp_path / "utils.py").write_text("# utils")

        # Init with qualifying_interest
        trug = tinit(tmp_path, name="HubTest", qualifying_interest="Best Burgers")
        root = trug["nodes"][0]
        assert root["properties"]["qualifying_interest"] == "Best Burgers"

        # Add files
        tadd(tmp_path, ["main.py", "utils.py"])

        # Link with weight
        trug = tlink(tmp_path, "main_py", "utils_py", "DEPENDS_ON", weight=0.9)
        edge = trug["edges"][0]
        assert edge["weight"] == 0.9

        # Validate — should pass cleanly
        result = validate_trug(trug)
        assert not any(e.code == "INVALID_EDGE_WEIGHT" for e in result.errors)

        # Render — weight should appear in architecture output
        output = render_architecture(trug)
        assert "0.90" in output
