"""Tests for AAA TRUG markdown renderer."""

import json
from pathlib import Path

from trugs_tools.aaa_renderer import _load_trug, render_aaa_trug


CANONICAL_PATH = (
    Path(__file__).resolve().parents[2]
    / "TRUGS_AAA"
    / "examples"
    / "canonical_example.trug.json"
)


def _canonical_data():
    return json.loads(CANONICAL_PATH.read_text(encoding="utf-8"))


def test_load_trug_accepts_dict_path_and_json_string():
    data = _canonical_data()
    assert _load_trug(data)["type"] == "AAA"
    assert _load_trug(CANONICAL_PATH)["type"] == "AAA"
    assert _load_trug(json.dumps(data))["type"] == "AAA"


def test_render_aaa_trug_includes_root_and_phases():
    output = render_aaa_trug(CANONICAL_PATH)
    assert output.startswith("<!-- GENERATED BY TRUGS — DO NOT EDIT -->")
    assert "# #581-6: TRUG Authoring + Governance" in output
    assert "**Issue Number:** 596" in output
    assert "**Folder:** PERAGO" in output
    assert "**Status:** COMPLETE" in output
    assert "**Created:** 2026-02-20" in output
    assert "## VISION" in output
    assert "## FEASIBILITY" in output
    assert "## SPECIFICATIONS" in output
    assert "## ARCHITECTURE" in output
    assert "## CODING" in output
    assert "## TESTING" in output
    assert "## DEPLOYMENT" in output
    assert output.index("## VISION") < output.index("## FEASIBILITY") < output.index("## SPECIFICATIONS")


def test_render_aaa_trug_renders_all_required_node_type_outputs():
    output = render_aaa_trug(CANONICAL_PATH)
    # TASK + AUDIT
    assert "- [x] [VALIDATE] Implement autonomous TRUG authoring pipeline" in output
    assert "  **AUDIT:**" in output
    assert "  - [x] Gate 1 — Tests: Targeted and regression tests pass" in output
    # RISK
    assert "| Risk | Severity | Mitigation | Source |" in output
    assert "Generated TRUGs may drift from protocol constraints" in output
    # DEPENDENCY
    assert "| Dependency | Type | Version | Status |" in output
    assert "TRUGS protocol branch definitions" in output
    # RESEARCH_SOURCE
    assert "| Source | URL | Accessed | Relevance |" in output
    # ADR
    assert "| ADR | Decision | Rationale | Status |" in output
    assert "ADR-596-01" in output
    # QUALITY_GATE
    assert "- [x] All validation and governance tests passing: pytest suite passes and protocol checks return zero errors" in output
    # SUB_ISSUE
    assert "| # | Title | Type | Status |" in output
    assert "| 593 | AAA Generation — predecessor task | A | COMPLETE |" in output


def test_render_aaa_trug_not_applicable_phase_message():
    data = _canonical_data()
    for node in data["nodes"]:
        if node["id"] == "phase_deployment":
            node["properties"]["status"] = "NOT_APPLICABLE"
            break
    output = render_aaa_trug(data)
    assert "## DEPLOYMENT" in output
    assert "*Not applicable for this project.*" in output
