"""AAA TRUG renderer - compiles aaa_v1 TRUG JSON into AAA.md markdown."""

import json
from pathlib import Path
from typing import Any, Dict, List, Tuple


GENERATED_HEADER = "<!-- GENERATED BY TRUGS — DO NOT EDIT -->"
PHASE_ORDER = [
    "VISION",
    "FEASIBILITY",
    "SPECIFICATIONS",
    "ARCHITECTURE",
    "CODING",
    "TESTING",
    "DEPLOYMENT",
]


def _load_trug(trug: Any) -> Dict[str, Any]:
    """Accept dict, path, or string; return parsed TRUG dict."""
    if isinstance(trug, dict):
        return trug
    if isinstance(trug, Path):
        return json.loads(trug.read_text(encoding="utf-8"))
    if isinstance(trug, str):
        stripped = trug.strip()
        if stripped.startswith("{"):
            return json.loads(stripped)
        return json.loads(Path(stripped).read_text(encoding="utf-8"))
    raise TypeError(f"Expected dict, str, or Path; got {type(trug).__name__}")


def _node_map(trug: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    return {node.get("id"): node for node in trug.get("nodes", []) if node.get("id")}


def _node_children(trug: Dict[str, Any], parent_id: str) -> List[Dict[str, Any]]:
    children = [n for n in trug.get("nodes", []) if n.get("parent_id") == parent_id]
    children.sort(key=lambda n: (n.get("type", ""), n.get("properties", {}).get("name", n.get("id", ""))))
    return children


def _find_root(data: Dict[str, Any]) -> Dict[str, Any]:
    for node in data.get("nodes", []):
        if node.get("type") == "AAA":
            return node
    for node in data.get("nodes", []):
        if node.get("parent_id") is None:
            return node
    raise ValueError("No AAA root node found in TRUG (expected node type 'AAA' or parent_id=None)")


def _is_checked(status: Any) -> bool:
    value = str(status or "").upper()
    return value in {"COMPLETE", "PASS", "DONE", "✅"}


def _task_line(task: Dict[str, Any]) -> str:
    props = task.get("properties", {})
    checked = "x" if _is_checked(props.get("status")) else " "
    name = props.get("name", task.get("id", "unnamed task"))
    op = props.get("operation")
    if op:
        return f"- [{checked}] [{str(op).upper()}] {name}"
    return f"- [{checked}] {name}"


def _paired_audits(data: Dict[str, Any], task_id: str, nmap: Dict[str, Dict[str, Any]]) -> List[Dict[str, Any]]:
    audits: List[Dict[str, Any]] = []
    for edge in data.get("edges", []):
        if edge.get("relation") == "audits" and edge.get("to_id") == task_id:
            node = nmap.get(edge.get("from_id"))
            if node and node.get("type") == "AUDIT":
                audits.append(node)
    audits.sort(key=lambda n: n.get("properties", {}).get("name", n.get("id", "")))
    return audits


def _append_table(lines: List[str], headers: List[str], rows: List[Tuple[Any, ...]]) -> None:
    """Append a markdown table when rows are present."""
    if not rows:
        return
    lines.append(f"| {' | '.join(headers)} |")
    lines.append(f"| {' | '.join(['---'] * len(headers))} |")
    for row in rows:
        lines.append(f"| {' | '.join(str(v) for v in row)} |")
    lines.append("")


# AGENT claude SHALL DEFINE FUNCTION render_aaa_trug.
def render_aaa_trug(trug: Any) -> str:
    """Render AAA.md from an AAA TRUG dict/path/json-string."""
    data = _load_trug(trug)
    nmap = _node_map(data)
    root = _find_root(data)
    root_props = root.get("properties", {})

    phases = _node_children(data, root["id"])
    phases.sort(
        key=lambda n: (
            PHASE_ORDER.index(str(n.get("properties", {}).get("name", "")).upper())
            if str(n.get("properties", {}).get("name", "")).upper() in PHASE_ORDER
            else len(PHASE_ORDER),
            n.get("properties", {}).get("name", n.get("id", "")),
        )
    )

    lines: List[str] = [
        GENERATED_HEADER,
        "",
        f"# {root_props.get('name', 'AAA')}",
        "",
        f"**Issue Number:** {root_props.get('issue_number', '')}",
        f"**Folder:** {root_props.get('folder', '')}",
        f"**Status:** {root_props.get('status', '')}",
        f"**Created:** {root_props.get('created', '')}",
        "",
        "---",
        "",
    ]

    for phase in phases:
        if phase.get("type") != "PHASE":
            continue

        phase_props = phase.get("properties", {})
        phase_name = phase_props.get("name", phase.get("id", "PHASE"))
        phase_status = phase_props.get("status", "")
        phase_gate = phase_props.get("quality_gate", "")

        lines.append(f"## {phase_name}")
        lines.append("")
        lines.append(f"**Phase Status:** {phase_status}")
        lines.append(f"**Quality Gate:** {phase_gate}")
        lines.append("")

        if str(phase_status).upper() == "NOT_APPLICABLE":
            lines.append("*Not applicable for this project.*")
            lines.append("")
            continue

        children = _node_children(data, phase.get("id"))
        tasks = [n for n in children if n.get("type") == "TASK"]
        risks = [n for n in children if n.get("type") == "RISK"]
        dependencies = [n for n in children if n.get("type") == "DEPENDENCY"]
        sources = [n for n in children if n.get("type") == "RESEARCH_SOURCE"]
        adrs = [n for n in children if n.get("type") == "ADR"]
        gates = [n for n in children if n.get("type") == "QUALITY_GATE"]
        sub_issues = [n for n in children if n.get("type") == "SUB_ISSUE"]

        for task in tasks:
            lines.append(_task_line(task))
            for audit in _paired_audits(data, task.get("id", ""), nmap):
                audit_props = audit.get("properties", {})
                checked = "x" if _is_checked(audit_props.get("status")) else " "
                lines.append("  **AUDIT:**")
                lines.append(f"  - [{checked}] Gate 1 — Tests: {audit_props.get('gate_1_tests', '')}")
                lines.append(f"  - [{checked}] Gate 2 — Coverage: {audit_props.get('gate_2_coverage', '')}")
                lines.append(f"  - [{checked}] Gate 3 — Logic: {audit_props.get('gate_3_logic', '')}")
                lines.append(f"  - [{checked}] Gate 4 — Integration: {audit_props.get('gate_4_integration', '')}")
            lines.append("")

        risk_rows = [
            (
                n.get("properties", {}).get("name", n.get("id", "")),
                n.get("properties", {}).get("severity", ""),
                n.get("properties", {}).get("mitigation", ""),
                n.get("properties", {}).get("source", ""),
            )
            for n in risks
        ]
        _append_table(lines, ["Risk", "Severity", "Mitigation", "Source"], risk_rows)

        dependency_rows = [
            (
                n.get("properties", {}).get("name", n.get("id", "")),
                n.get("properties", {}).get("type", ""),
                n.get("properties", {}).get("version", ""),
                n.get("properties", {}).get("status", ""),
            )
            for n in dependencies
        ]
        _append_table(lines, ["Dependency", "Type", "Version", "Status"], dependency_rows)

        source_rows = [
            (
                n.get("properties", {}).get("name", n.get("id", "")),
                n.get("properties", {}).get("url", ""),
                n.get("properties", {}).get("accessed", ""),
                n.get("properties", {}).get("relevance", ""),
            )
            for n in sources
        ]
        _append_table(lines, ["Source", "URL", "Accessed", "Relevance"], source_rows)

        adr_rows = [
            (
                n.get("properties", {}).get("adr_id", ""),
                n.get("properties", {}).get("decision", ""),
                n.get("properties", {}).get("rationale", ""),
                n.get("properties", {}).get("status", ""),
            )
            for n in adrs
        ]
        _append_table(lines, ["ADR", "Decision", "Rationale", "Status"], adr_rows)

        for gate in gates:
            gate_props = gate.get("properties", {})
            checked = "x" if _is_checked(gate_props.get("status")) else " "
            lines.append(f"- [{checked}] {gate_props.get('name', gate.get('id', ''))}: {gate_props.get('condition', '')}")
        if gates:
            lines.append("")

        sub_rows = [
            (
                n.get("properties", {}).get("issue_number", ""),
                n.get("properties", {}).get("name", n.get("id", "")),
                n.get("properties", {}).get("type", ""),
                n.get("properties", {}).get("status", ""),
            )
            for n in sub_issues
        ]
        _append_table(lines, ["#", "Title", "Type", "Status"], sub_rows)

    return "\n".join(lines).rstrip() + "\n"
