"""agent_instructions_renderer — renders .github/agent_instructions.trug.json
into .github/copilot-instructions.md.

Output is deterministic: same TRUG input → byte-identical output.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Union


GENERATED_HEADER = (
    "<!-- This file is auto-generated by trugs-agent-render — do not edit directly. -->"
)
_SOURCE_COMMENT = (
    "<!-- SOURCE OF TRUTH: .github/agent_instructions.trug.json -->"
)
_TITLE = "# TRUGS_DEVELOPMENT: Instructions for LLM and CoPilot Agents."


# ─── Loader ───────────────────────────────────────────────────────────


def _load_trug(trug: Any) -> Dict[str, Any]:
    """Accept dict, path, or string; return parsed TRUG dict."""
    if isinstance(trug, dict):
        return trug
    if isinstance(trug, (str, Path)):
        with open(Path(trug), "r", encoding="utf-8") as f:
            return json.load(f)
    raise TypeError(f"Expected dict, str, or Path; got {type(trug)}")


# ─── Section renderers ────────────────────────────────────────────────


def _render_tutorial(n: Dict) -> str:
    """Render tutorial_what_is_a_trug (STANDARD / FOUNDATIONAL)."""
    p = n.get("properties", {})
    lines: List[str] = [f"## {n['label']}"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    defn = p.get("definition", "")
    if defn:
        lines.append(defn)
        lines.append("")

    cvb = p.get("core_vs_branches", {})
    if cvb:
        lines.append("**CORE vs BRANCHES:**")
        for key, val in cvb.items():
            lines.append(f"- **{key}** — {val}")
        lines.append("")

    why = p.get("why_it_matters", "")
    if why:
        lines.append(f"**Why it matters:** {why}")
        lines.append("")

    node_fields = p.get("seven_node_fields", {})
    if node_fields:
        formatted = ", ".join(f"`{k}`" for k in node_fields)
        lines.append(f"**7 required node fields:** {formatted}")
        for field, desc_text in node_fields.items():
            lines.append(f"- `{field}` — {desc_text}")
        lines.append("")

    edge_fields = p.get("three_edge_fields", {})
    if edge_fields:
        core_keys = [k for k in edge_fields if k not in ("bidirectionality_rule",)]
        formatted = ", ".join(f"`{k}`" for k in core_keys)
        lines.append(f"**3 required edge fields:** {formatted}")
        bidir = edge_fields.get("bidirectionality_rule", "")
        if bidir:
            lines.append(f"- **Bidirectionality rule:** {bidir}")
        lines.append("")

    kp = p.get("key_principle", "")
    if kp:
        lines.append(f"**Key principle:** {kp}")
        lines.append("")

    fc = p.get("file_conventions", {})
    if fc:
        lines.append("**Common TRUG files:**")
        for fname, fdesc in fc.items():
            lines.append(f"- `{fname}` — {fdesc}")
        lines.append("")

    pr = p.get("protocol_reference", "")
    if pr:
        lines.append(pr)

    return "\n".join(lines)


def _render_protected(nodes: List[Dict]) -> str:
    """Render all CONSTRAINT nodes under a single PROTECTED section."""
    lines: List[str] = ["## PROTECTED - DO NOT MODIFY"]
    lines.append("")

    for n in nodes:
        p = n.get("properties", {})
        desc = p.get("description", "")
        if desc:
            lines.append(desc)

        paths = p.get("paths", [])
        for path in paths:
            lines.append(f"- `{path}`")

        files = p.get("files", [])
        if files:
            gen = p.get("generator", "")
            wf = p.get("workflow", "")
            suffix = ""
            if gen:
                suffix += f" — **auto-generated** by `{gen}`"
            if wf:
                suffix += f" via `{wf}`"
            suffix += ". Never hand-edit; changes will be overwritten."
            for f in files:
                lines.append(f"- `{f}`{suffix}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_project_org(nodes: List[Dict]) -> str:
    """Render Interactive + Agentic workflow nodes under Project Organization."""
    lines: List[str] = ["## Project Organization & Agentic Coding"]
    lines.append("")
    lines.append("**Two Workflows:**")

    for i, n in enumerate(nodes, 1):
        p = n.get("properties", {})
        desc = p.get("description", "")
        lines.append(f"{i}. **{n['label']}:** {desc}")

    return "\n".join(lines)


def _render_doc_standards(nodes: List[Dict]) -> str:
    """Render CRITICAL standard nodes + four-file pattern under DOCUMENTATION STANDARDS."""
    lines: List[str] = ["## DOCUMENTATION STANDARDS"]
    lines.append("")

    critical_nodes = [n for n in nodes if n.get("properties", {}).get("severity") == "CRITICAL"]
    four_file = next((n for n in nodes if n["id"] == "standard_four_file_pattern"), None)

    for n in critical_nodes:
        p = n.get("properties", {})
        desc = p.get("description", "")
        lines.append(f"> **🚨 CRITICAL: {desc}**")

    if critical_nodes:
        lines.append("")

    if four_file:
        p = four_file.get("properties", {})
        lines.append(f"### {four_file['label']}")
        lines.append("")

        files = p.get("files", {})
        if files:
            lines.append("| File | Audience | Content |")
            lines.append("|------|----------|---------|")
            for fname, finfo in files.items():
                audience = finfo.get("audience", "")
                content = finfo.get("content", "")
                note = finfo.get("note", "")
                note_suffix = f" ({note})" if note else ""
                lines.append(f"| **{fname}** | {audience} | {content}{note_suffix} |")
            lines.append("")

        th = p.get("truth_hierarchy", "")
        if th:
            lines.append(th)

    return "\n".join(lines)


def _render_branching(n: Dict) -> str:
    """Render rule_branching (RULE / HARD)."""
    p = n.get("properties", {})
    lines: List[str] = ["## BRANCHING RULES (HARD RULE)"]
    lines.append("")

    ur = p.get("universal_rule", "")
    if ur:
        lines.append(f"**ALL changes (code, JSON, markdown):** {ur}")

    ir = p.get("issue_rule", "")
    if ir:
        lines.append(f"**All development work:** {ir}")

    dr = p.get("docs_rule", "")
    if dr:
        lines.append(f"**Documentation/markdown changes:** {dr}")

    steps = p.get("branch_steps", [])
    if steps:
        lines.append("")
        for i, step in enumerate(steps, 1):
            lines.append(f"{i}. {step}")

    return "\n".join(lines)


def _render_naming(n: Dict) -> str:
    """Render convention_naming (CONVENTION)."""
    p = n.get("properties", {})
    lines: List[str] = ["## DOCUMENT NAMING CONVENTION"]
    lines.append("")

    det = p.get("deterministic_files", {})
    if det:
        desc = det.get("description", "")
        files = det.get("files", [])
        file_str = ", ".join(f"`{f}`" for f in files)
        lines.append(f"**Deterministic files** ({desc}):")
        lines.append(file_str)
        lines.append("")

    hc = p.get("human_created_files", {})
    if hc:
        pattern = hc.get("pattern", "")
        type_case = hc.get("type_case", "")
        desc_case = hc.get("description_case", "")
        valid_types = hc.get("valid_types", [])
        examples = hc.get("examples", [])

        lines.append(f"**Human-created files** must follow: `{pattern}`")
        if type_case:
            lines.append(f"- TYPE is {type_case}: " + ", ".join(f"`{t}`" for t in valid_types))
        if desc_case:
            lines.append(f"- Description is {desc_case}")
        if examples:
            lines.append("- Examples: " + ", ".join(f"`{e}`" for e in examples))
        lines.append("")

    aaa = p.get("aaa_workflow", {})
    if aaa:
        aaa_desc = aaa.get("description", "")
        if aaa_desc:
            lines.append(f"**AAA workflow:** {aaa_desc}")

        phases = aaa.get("aaa_phase_types", {})
        if phases:
            for typ, phase_desc in phases.items():
                lines.append(f"- `{typ}_` — {phase_desc}")
        lines.append("")

        lifecycle = aaa.get("lifecycle", "")
        if lifecycle:
            lines.append(lifecycle)

    return "\n".join(lines)


def _render_archive(n: Dict) -> str:
    """Render convention_archive (CONVENTION)."""
    p = n.get("properties", {})
    lines: List[str] = ["## ARCHIVE CONVENTION"]
    lines.append("")

    prefix = p.get("prefix", "zzz_")
    desc = p.get("description", "")
    lines.append(f"Files prefixed with `{prefix}` are {desc.lower().replace('files prefixed with zzz_ are ', '')}".replace(
        'zzz_', f'{prefix}'
    ))
    lines.append("")

    llm = p.get("llm_rule", "")
    if llm:
        lines.append(f"- **LLMs:** {llm}")

    trug = p.get("trug_rule", "")
    if trug:
        lines.append(f"- **TRUGs:** {trug}")

    rationale = p.get("rationale", "")
    if rationale:
        lines.append(f"- {rationale}")

    return "\n".join(lines)


def _render_trug_build(n: Dict) -> str:
    """Render rule_trug_build (RULE / HARD)."""
    p = n.get("properties", {})
    lines: List[str] = ["## FOLDER TRUG BUILD RULES (HARD RULE)"]
    lines.append("")

    constraints = p.get("constraints", [])
    if constraints:
        constraint_str = " ".join(constraints)
        lines.append(f"> **🚨 {constraint_str}**")
        lines.append("")

    lines.append("When creating or updating a `folder.trug.json`:")
    steps = p.get("steps", [])
    for i, step in enumerate(steps, 1):
        lines.append(f"{i}. {step}")
    lines.append("")

    principle = p.get("principle", "")
    if principle:
        lines.append(principle)

    return "\n".join(lines)


def _render_execution(n: Dict) -> str:
    """Render rule_execution (RULE)."""
    p = n.get("properties", {})
    lines: List[str] = ["## EXECUTION RULES"]
    lines.append("")

    rules = p.get("rules", [])
    for rule in rules:
        lines.append(f"- {rule}")

    return "\n".join(lines)


def _render_sub_issues(n: Dict) -> str:
    """Render workflow_sub_issues (WORKFLOW)."""
    p = n.get("properties", {})
    lines: List[str] = ["## SUB-ISSUES"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    link_api = p.get("link_api", {})
    if link_api:
        lines.append("**To link a sub-issue via API:**")
        for step_key in sorted(link_api):
            step_val = link_api[step_key]
            lines.append(f"   `{step_val}`")
        lines.append("")

    pattern = p.get("pattern", [])
    if pattern:
        lines.append("**Pattern:**")
        for item in pattern:
            lines.append(f"- {item}")

    return "\n".join(lines)


def _render_commands(n: Dict) -> str:
    """Render the commands STANDARD node (CLI reference)."""
    p = n.get("properties", {})
    lines: List[str] = [f"## {n['label']}"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    trugs_tools = p.get("trugs_tools", {})
    if trugs_tools:
        lines.append("**trugs-tools commands:**")
        for cmd, cmd_desc in trugs_tools.items():
            lines.append(f"- `{cmd}` — {cmd_desc}")
        lines.append("")

    perago = p.get("perago", {})
    if perago:
        lines.append("**perago commands:**")
        for cmd, cmd_desc in perago.items():
            lines.append(f"- `{cmd}` — {cmd_desc}")

    return "\n".join(lines)


def _render_generic_rule(n: Dict) -> str:
    """Generic renderer for RULE nodes not explicitly handled."""
    p = n.get("properties", {})
    severity = p.get("severity", "")
    hard_suffix = " (HARD RULE)" if severity == "HARD" else ""
    lines: List[str] = [f"## {n['label']}{hard_suffix}"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    # Render any list-type properties
    for key, val in p.items():
        if key in ("severity", "description"):
            continue
        if isinstance(val, list):
            for item in val:
                lines.append(f"- {item}")
        elif isinstance(val, str):
            lines.append(f"**{key}:** {val}")

    return "\n".join(lines)


def _render_references(nodes: List[Dict]) -> str:
    """Render all REFERENCE nodes under a single References section."""
    lines: List[str] = ["## References"]
    lines.append("")

    for n in nodes:
        p = n.get("properties", {})
        label = n.get("label", n.get("id", "Reference"))
        path = p.get("path", "")
        lines.append(f"**{label}:** `{path}`")

        key_files = p.get("key_files", {})
        if key_files:
            for fname, fdesc in key_files.items():
                lines.append(f"- `{fname}` — {fdesc}")

        lines.append("")

    return "\n".join(lines).rstrip()


# ─── Main renderer ────────────────────────────────────────────────────


def render_agent_instructions(
    trug: Any,
    render_date: Optional[str] = None,
) -> str:
    """Render agent_instructions.trug.json to copilot-instructions.md content.

    Args:
        trug: TRUG dict, file path, or JSON string.
        render_date: Unused — accepted for API consistency with other renderers.

    Returns:
        Full markdown content for copilot-instructions.md as a string.
    """
    data = _load_trug(trug)
    nodes = data.get("nodes", [])
    nmap: Dict[str, Dict] = {n["id"]: n for n in nodes}

    parts: List[str] = []

    # ── File header ──────────────────────────────────────────────────
    parts.append(f"{_TITLE}\n\n{_SOURCE_COMMENT}\n{GENERATED_HEADER}")

    # ── 1. What Is a TRUG (FOUNDATIONAL) ─────────────────────────────
    if "tutorial_what_is_a_trug" in nmap:
        parts.append(_render_tutorial(nmap["tutorial_what_is_a_trug"]))

    # ── 2. PROTECTED — all CONSTRAINT nodes ──────────────────────────
    constraint_nodes = [n for n in nodes if n.get("type") == "CONSTRAINT"]
    if constraint_nodes:
        parts.append(_render_protected(constraint_nodes))

    # ── 3. Project Organization — interactive + agentic workflows ────
    org_ids = ["workflow_interactive", "workflow_agentic"]
    org_nodes = [nmap[i] for i in org_ids if i in nmap]
    if org_nodes:
        parts.append(_render_project_org(org_nodes))

    # ── 4. Documentation Standards ───────────────────────────────────
    doc_ids = ["standard_check_aaa", "standard_read_trug", "standard_four_file_pattern"]
    doc_nodes = [nmap[i] for i in doc_ids if i in nmap]
    if doc_nodes:
        parts.append(_render_doc_standards(doc_nodes))

    # ── 5. Branching Rules ────────────────────────────────────────────
    if "rule_branching" in nmap:
        parts.append(_render_branching(nmap["rule_branching"]))

    # ── 6. Document Naming Convention ────────────────────────────────
    if "convention_naming" in nmap:
        parts.append(_render_naming(nmap["convention_naming"]))

    # ── 7. Archive Convention ─────────────────────────────────────────
    if "convention_archive" in nmap:
        parts.append(_render_archive(nmap["convention_archive"]))

    # ── 8. Folder TRUG Build Rules ────────────────────────────────────
    if "rule_trug_build" in nmap:
        parts.append(_render_trug_build(nmap["rule_trug_build"]))

    # ── 9. Execution Rules ────────────────────────────────────────────
    if "rule_execution" in nmap:
        parts.append(_render_execution(nmap["rule_execution"]))

    # ── 10. Sub-Issues ────────────────────────────────────────────────
    if "workflow_sub_issues" in nmap:
        parts.append(_render_sub_issues(nmap["workflow_sub_issues"]))

    # ── 11. commands ─────────────────────────────────────────────────
    if "commands" in nmap:
        parts.append(_render_commands(nmap["commands"]))

    # ── 12. Any remaining nodes not yet rendered (generic, non-ref) ──
    rendered_ids = {
        "tutorial_what_is_a_trug",
        "workflow_interactive", "workflow_agentic",
        "standard_check_aaa", "standard_read_trug", "standard_four_file_pattern",
        "rule_branching", "convention_naming", "convention_archive",
        "rule_trug_build", "rule_execution", "workflow_sub_issues",
        "commands",
    } | {n["id"] for n in constraint_nodes}

    for node in nodes:
        if node["id"] in rendered_ids or node.get("type") == "REFERENCE":
            continue
        parts.append(_render_generic_rule(node))

    # ── 13. References ────────────────────────────────────────────────
    ref_nodes = [n for n in nodes if n.get("type") == "REFERENCE"]
    if ref_nodes:
        parts.append(_render_references(ref_nodes))

    return "\n\n".join(parts) + "\n"
