"""claude_instructions_renderer — renders .github/agent_instructions.trug.json
into CLAUDE.md for Claude Code.

Output is deterministic: same TRUG input → byte-identical output.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


GENERATED_HEADER = "<!-- This file is auto-generated by trugs-claude-render — do not edit directly. -->"
_SOURCE_COMMENT = "<!-- SOURCE OF TRUTH: .github/agent_instructions.trug.json -->"
_TITLE = "# CLAUDE.md"
_SUBTITLE = "This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository."


# ─── Loader ───────────────────────────────────────────────────────────


def _load_trug(trug: Any) -> Dict[str, Any]:
    """Accept dict, path, or string; return parsed TRUG dict."""
    if isinstance(trug, dict):
        return trug
    if isinstance(trug, (str, Path)):
        with open(Path(trug), "r", encoding="utf-8") as f:
            return json.load(f)
    raise TypeError(f"Expected dict, str, or Path; got {type(trug)}")


# ─── TRL block helper ─────────────────────────────────────────────────


def _render_trl_block(instructions: List[str]) -> str:
    """Render a list of TRL instructions as a <trl> block."""
    if not instructions:
        return ""
    lines = ["", "<trl>"]
    for inst in instructions:
        lines.append(inst)
    lines.append("</trl>")
    return "\n".join(lines)


# ─── Section renderers ────────────────────────────────────────────────


def _render_header() -> str:
    """File header with CLAUDE.md title."""
    return f"{_TITLE}\n\n{_SUBTITLE}"


def _render_what_is_trugs(n: Dict) -> str:
    """Render tutorial_what_is_a_trug as a concise overview."""
    p = n.get("properties", {})
    lines: List[str] = ["## What This Repository Is"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    defn = p.get("definition", "")
    if defn:
        lines.append(defn)
        lines.append("")

    cvb = p.get("core_vs_branches", {})
    if cvb:
        for key, val in cvb.items():
            lines.append(f"- **{key}** — {val}")
        lines.append("")

    kp = p.get("key_principle", "")
    if kp:
        lines.append(f"**Key principle:** {kp}")

    protocol = p.get("protocol_reference", "")
    if protocol:
        lines.append("")
        lines.append(protocol)

    # TRL primer
    trl = p.get("trl", {})
    if trl:
        lines.append("")
        lines.append("## TRUGS Language (TRL) — 190-Word Vocabulary")
        lines.append("")
        what = trl.get("what", "")
        if what:
            lines.append(what)
            lines.append("")

        nouns = trl.get("nouns", {})
        if nouns:
            lines.append("### Nouns — things that exist (become graph nodes)")
            for category, words in nouns.items():
                lines.append(f"- **{category.title()}:** {words}")
            lines.append("")

        verbs = trl.get("verbs", {})
        if verbs:
            lines.append("### Verbs — actions (become operation nodes)")
            for category, words in verbs.items():
                lines.append(f"- **{category.title()}:** {words}")
            lines.append("")

        modals = trl.get("modals", "")
        if modals:
            lines.append(f"### Modals — {modals}")
            lines.append("")

        for section_key, section_title in [
            ("adjectives", "Adjectives — modify nouns (become node properties)"),
            ("adverbs", "Adverbs — modify verbs (become operation properties)"),
            ("prepositions", "Prepositions — relationships (become graph edges)"),
            ("conjunctions", "Conjunctions — connect clauses"),
            ("articles", "Articles — scope (become query selectors)"),
            ("pronouns", "Pronouns — back-references"),
            ("sugar", "Sugar — 'words compile to nothing (human readability only)"),
        ]:
            val = trl.get(section_key, "")
            if val:
                lines.append(f"**{section_title}:** {val}")
                lines.append("")

        example = trl.get("parse_example", {})
        if example:
            lines.append("### How to Read a TRL Sentence")
            lines.append("")
            lines.append(f"`{example.get('sentence', '')}`")
            lines.append("")
            lines.append(example.get("parse", ""))
            lines.append("")

        steps = trl.get("execution_steps", [])
        if steps:
            lines.append("### How to Execute a `<trl>` Block")
            lines.append("")
            for i, step in enumerate(steps, 1):
                lines.append(f"{i}. {step}")

    return "\n".join(lines)


def _render_protected(constraint_nodes: List[Dict], archive_node: Optional[Dict]) -> str:
    """Render protected paths and deterministic files."""
    lines: List[str] = ["## Protected Paths — Never Modify"]
    lines.append("")

    all_trl: List[str] = []
    for n in constraint_nodes:
        p = n.get("properties", {})
        paths = p.get("paths", [])
        for path in paths:
            lines.append(f"- `{path}`")

        files = p.get("files", [])
        if files:
            gen = p.get("generator", "")
            for f in files:
                suffix = f" — auto-generated nightly by `{gen}`" if gen else ""
                lines.append(f"- `{f}` files{suffix}")

        all_trl.extend(p.get("trl_instruction", []))

    if archive_node:
        p = archive_node.get("properties", {})
        prefix = p.get("prefix", "zzz_")
        llm_rule = p.get("llm_rule", "")
        lines.append(f"- `{prefix}*` files/folders — Archived; {llm_rule.rstrip('.')}")
        all_trl.extend(p.get("trl_instruction", []))

    if all_trl:
        lines.append(_render_trl_block(all_trl))

    return "\n".join(lines)


def _render_commands(n: Dict) -> str:
    """Render CLI commands as setup & reference section."""
    p = n.get("properties", {})
    lines: List[str] = ["## Setup & Commands"]
    lines.append("")

    install_desc = p.get("description", "")
    if install_desc:
        # Extract install commands from the description
        lines.append("```bash")
        if "pip install -e TRUGS_TOOLS/" in install_desc:
            lines.append("# Install CLI tools (required for most work)")
            lines.append("pip install -e TRUGS_TOOLS/")
        if "pip install -e PERAGO/" in install_desc:
            lines.append("")
            lines.append("# Install autonomous agent")
            lines.append("pip install -e PERAGO/")
        lines.append("```")
        lines.append("")

    trugs_tools = p.get("trugs_tools", {})
    if trugs_tools:
        lines.append("### TRUG Validation & Sync")
        lines.append("")
        lines.append("```bash")
        for cmd, cmd_desc in trugs_tools.items():
            lines.append(f"{cmd}  # {cmd_desc}")
        lines.append("```")
        lines.append("")

    perago = p.get("perago", {})
    if perago:
        lines.append("### Perago Agent")
        lines.append("")
        lines.append("```bash")
        for cmd, cmd_desc in perago.items():
            lines.append(f"{cmd}  # {cmd_desc}")
        lines.append("```")

    return "\n".join(lines)


def _render_branching(n: Dict) -> str:
    """Render branching rules."""
    p = n.get("properties", {})
    lines: List[str] = ["## Development Workflow"]
    lines.append("")
    lines.append("### Branching (Hard Rule)")
    lines.append("")

    ur = p.get("universal_rule", "")
    if ur:
        lines.append(ur)
        lines.append("")

    ndc = p.get("no_direct_commits", "")
    if ndc:
        lines.append(f"- **No direct commits:** {ndc}")

    ir = p.get("issue_rule", "")
    if ir:
        lines.append(f"- {ir}")

    dr = p.get("docs_rule", "")
    if dr:
        lines.append(f"- {dr}")

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_hitm(n: Dict) -> str:
    """Render HITM constraint as a hard rule section."""
    p = n.get("properties", {})
    lines: List[str] = ["### Human-In-The-Middle — HITM (Hard Rule)"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)

    scope = p.get("scope", [])
    if scope:
        lines.append("")
        lines.append("Prohibited actions:")
        for item in scope:
            lines.append(f"- `{item}`")

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_maintenance(n: Dict) -> str:
    """Render maintenance workflow as two command sections."""
    p = n.get("properties", {})
    lines: List[str] = ["### Session Maintenance"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    maint = p.get("maintenance_command", {})
    if maint:
        trigger = maint.get("trigger", "/maintenance")
        purpose = maint.get("purpose", "")
        lines.append(f"**`{trigger}`** — Mid-session checkpoint. {purpose}")
        lines.append("")
        tasks = maint.get("tasks", [])
        for task in tasks:
            lines.append(f"- {task}")
        lines.append("")

    stop = p.get("stop_command", {})
    if stop:
        trigger = stop.get("trigger", "/stop")
        purpose = stop.get("purpose", "")
        lines.append(f"**`{trigger}`** — End-of-day shutdown. {purpose}")
        lines.append("")
        tasks = stop.get("tasks", [])
        for task in tasks:
            lines.append(f"- {task}")
        lines.append("")

    dc = p.get("decision_capture", {})
    if dc:
        method = dc.get("method", "")
        if method:
            lines.append(f"**Decision capture:** {method}")

    return "\n".join(lines)


def _render_four_file_pattern(n: Dict) -> str:
    """Render four-file pattern as a table."""
    p = n.get("properties", {})
    lines: List[str] = ["### Four-File Pattern Per Folder"]
    lines.append("")

    files = p.get("files", {})
    if files:
        lines.append("| File | Audience | Content |")
        lines.append("|------|----------|---------|")
        for fname, finfo in files.items():
            audience = finfo.get("audience", "")
            content = finfo.get("content", "")
            note = finfo.get("note", "")
            note_suffix = f" ({note})" if note else ""
            lines.append(f"| **{fname}** | {audience} | {content}{note_suffix} |")
        lines.append("")

    th = p.get("truth_hierarchy", "")
    if th:
        lines.append(th)

    return "\n".join(lines)


def _render_naming(n: Dict) -> str:
    """Render document naming convention."""
    p = n.get("properties", {})
    lines: List[str] = ["### Document Naming Convention"]
    lines.append("")

    hc = p.get("human_created_files", {})
    if hc:
        pattern = hc.get("pattern", "")
        valid_types = hc.get("valid_types", [])
        lines.append(f"Human-created files: `{pattern}`")
        lines.append("")
        if valid_types:
            lines.append("Types: " + ", ".join(f"`{t}`" for t in valid_types))

    return "\n".join(lines)


def _render_trug_build_rules(n: Dict) -> str:
    """Render folder.trug.json rules."""
    p = n.get("properties", {})
    lines: List[str] = ["### folder.trug.json Rules"]
    lines.append("")

    principle = p.get("principle", "")
    if principle:
        lines.append(f"- **Ground truth** — {principle}")

    steps = p.get("steps", [])
    for step in steps:
        lines.append(f"- {step}")

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_execution(n: Dict) -> str:
    """Render execution rules."""
    p = n.get("properties", {})
    lines: List[str] = ["### Execution Rules"]
    lines.append("")

    rules = p.get("rules", [])
    for rule in rules:
        lines.append(f"- {rule}")

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_motivation_permanent(n: Dict) -> str:
    """Render motivation/principle permanence rule."""
    p = n.get("properties", {})
    desc = p.get("description", "")
    sync_rule = p.get("sync_rule", "")
    lines: List[str] = []
    if desc:
        lines.append(f"- **Permanent nodes:** {desc}")
    if sync_rule:
        lines.append(f"- **Sync rule:** {sync_rule}")

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_component_naming(n: Dict) -> str:
    """Render component naming / architecture notes."""
    p = n.get("properties", {})
    lines: List[str] = ["## Architecture Notes"]
    lines.append("")

    instruction = p.get("instruction", "")
    if instruction:
        lines.append(f"- **PERAGO agents:** {instruction}")

    return "\n".join(lines)


def _render_claude_code_integration(n: Dict) -> str:
    """Render Claude Code integration section: exclusive, memory, skills, rules, MCP, navigation."""
    p = n.get("properties", {})
    lines: List[str] = ["## Claude Code Integration"]
    lines.append("")

    exclusive = p.get("exclusive", "")
    if exclusive:
        lines.append(f"**{exclusive}**")
        lines.append("")

    mem = p.get("memory", {})
    if mem:
        lines.append("### Memory System")
        lines.append(mem.get("description", ""))
        lines.append("")
        mem_trl = mem.get("trl_instruction", [])
        if mem_trl:
            lines.append(_render_trl_block(mem_trl))
            lines.append("")

    skills = p.get("skills", {})
    if skills:
        lines.append("### Skills (custom slash commands)")
        for cmd, desc in skills.items():
            lines.append(f"- `{cmd}` — {desc}")
        lines.append("")

    rules = p.get("rules", {})
    if rules:
        lines.append("### Rules")
        for path, desc in rules.items():
            lines.append(f"- `{path}` — {desc}")
        lines.append("")

    mcp = p.get("mcp_tools", {})
    if mcp:
        lines.append("### MCP Tools Available")
        for name, desc in mcp.items():
            lines.append(f"- **{name}** — {desc}")
        lines.append("")

    nav = p.get("navigation", {})
    if nav:
        lines.append("### Navigation")
        if "start" in nav:
            lines.append(f"- **Start with:** {nav['start']}")
        if "then" in nav:
            lines.append(f"- **Then:** {nav['then']}")
        if "per_folder" in nav:
            lines.append(f"- **Per folder:** {nav['per_folder']}")

    return "\n".join(lines)


def _render_epic_first(n: Dict) -> str:
    """Render the EPIC-first rule."""
    p = n.get("properties", {})
    lines: List[str] = ["### Read EPIC Before Work (Hard Rule)"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    checks = p.get("what_to_check", [])
    if checks:
        for item in checks:
            lines.append(f"- {item}")
        lines.append("")

    also = p.get("also_check", "")
    if also:
        lines.append(also)

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_trug_vocabulary(n: Dict) -> str:
    """Render TRL vocabulary rule."""
    p = n.get("properties", {})
    lines: List[str] = ["### Use TRL Vocabulary When Writing TRUGs (Hard Rule)"]
    lines.append("")

    desc = p.get("description", "")
    if desc:
        lines.append(desc)
        lines.append("")

    rels = p.get("edge_relations", {})
    if rels:
        lines.append("**Edge relations (TRL prepositions):**")
        lines.append("")
        for category, words in rels.items():
            lines.append(f"- **{category.title()}:** {', '.join(words)}")
        lines.append("")

    where = p.get("where_to_find", "")
    if where:
        lines.append(where)
        lines.append("")

    mistakes = p.get("common_mistakes", [])
    if mistakes:
        lines.append("**Common mistakes:**")
        for m in mistakes:
            lines.append(f"- {m}")

    trl = p.get("trl_instruction", [])
    if trl:
        lines.append(_render_trl_block(trl))

    return "\n".join(lines)


def _render_references(nodes: List[Dict]) -> str:
    """Render reference nodes as a compact list."""
    lines: List[str] = ["## Key References"]
    lines.append("")

    for n in nodes:
        p = n.get("properties", {})
        label = n.get("label", n.get("id", "Reference"))
        path = p.get("path", "")
        key_files = p.get("key_files", {})
        if key_files:
            first_file = next(iter(key_files))
            first_desc = key_files[first_file]
            lines.append(f"- **{label}:** `{path}` — start with `{first_file}` ({first_desc.lower().rstrip('.')})")
        else:
            lines.append(f"- **{label}:** `{path}`")

    return "\n".join(lines)


# ─── Main renderer ────────────────────────────────────────────────────


# AGENT claude SHALL DEFINE FUNCTION render_claude_instructions.
def render_claude_instructions(
    trug: Any,
    render_date: Optional[str] = None,
) -> str:
    """Render agent_instructions.trug.json to CLAUDE.md content.

    Args:
        trug: TRUG dict, file path, or JSON string.
        render_date: Unused — accepted for API consistency with other renderers.

    Returns:
        Full markdown content for CLAUDE.md as a string.
    """
    data = _load_trug(trug)
    nodes = data.get("nodes", [])
    nmap: Dict[str, Dict] = {n["id"]: n for n in nodes}

    parts: List[str] = []

    # ── File header ──────────────────────────────────────────────────
    parts.append(_render_header())

    # ── 1. What This Repository Is ───────────────────────────────────
    if "tutorial_what_is_a_trug" in nmap:
        parts.append(_render_what_is_trugs(nmap["tutorial_what_is_a_trug"]))

    # ── 2. Protected paths ───────────────────────────────────────────
    constraint_nodes = [n for n in nodes if n.get("type") == "CONSTRAINT"]
    archive_node = nmap.get("convention_archive")
    if constraint_nodes or archive_node:
        parts.append(_render_protected(constraint_nodes, archive_node))

    # ── 3. Setup & Commands ──────────────────────────────────────────
    if "commands" in nmap:
        parts.append(_render_commands(nmap["commands"]))

    # ── 4. Development Workflow ──────────────────────────────────────
    if "rule_branching" in nmap:
        parts.append(_render_branching(nmap["rule_branching"]))

    # ── 4a. HITM ──────────────────────────────────────────────────────
    if "rule_hitm" in nmap:
        parts.append(_render_hitm(nmap["rule_hitm"]))

    # ── 4a2. Maintenance ─────────────────────────────────────────────
    if "workflow_maintenance" in nmap:
        parts.append(_render_maintenance(nmap["workflow_maintenance"]))

    # ── 4b. Four-File Pattern ────────────────────────────────────────
    if "standard_four_file_pattern" in nmap:
        parts.append(_render_four_file_pattern(nmap["standard_four_file_pattern"]))

    # ── 4b. Document Naming ──────────────────────────────────────────
    if "convention_naming" in nmap:
        parts.append(_render_naming(nmap["convention_naming"]))

    # ── 4c. folder.trug.json Rules ───────────────────────────────────
    if "rule_trug_build" in nmap:
        parts.append(_render_trug_build_rules(nmap["rule_trug_build"]))

    # ── 4d. Execution Rules ──────────────────────────────────────────
    if "rule_execution" in nmap:
        parts.append(_render_execution(nmap["rule_execution"]))

    # ── 4e. Motivation permanence ────────────────────────────────────
    if "rule_motivation_permanent" in nmap:
        parts.append(_render_motivation_permanent(nmap["rule_motivation_permanent"]))

    # ── 5. Claude Code Integration ─────────────────────────────────
    if "claude_code_integration" in nmap:
        parts.append(_render_claude_code_integration(nmap["claude_code_integration"]))

    # ── 5a. Read EPIC Before Work ────────────────────────────────────
    if "rule_epic_first" in nmap:
        parts.append(_render_epic_first(nmap["rule_epic_first"]))

    # ── 5b. TRL Vocabulary ───────────────────────────────────────────
    if "rule_trug_vocabulary" in nmap:
        parts.append(_render_trug_vocabulary(nmap["rule_trug_vocabulary"]))

    # ── 6. Architecture Notes ────────────────────────────────────────
    if "component_naming" in nmap:
        parts.append(_render_component_naming(nmap["component_naming"]))

    # ── 7. References ────────────────────────────────────────────────
    ref_nodes = [n for n in nodes if n.get("type") == "REFERENCE"]
    if ref_nodes:
        parts.append(_render_references(ref_nodes))

    return "\n\n".join(parts) + "\n"
