"""TRUGS renderer - compiles folder.trug.json into deterministic markdown files.

Renders three views from a single TRUG source of truth:
  - AAA.md:          Development tracking (9-phase format)
  - README.md:       Human-friendly orientation and quickstart
  - ARCHITECTURE.md: Dense technical reference for LLMs

All output is deterministic: same TRUG input → byte-identical output.
"""

import json
import warnings
from datetime import date
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple, Union

from trugs_store import InMemoryGraphStore, JsonFilePersistence


GENERATED_HEADER = "<!-- GENERATED BY TRUGS — DO NOT EDIT -->"


def _load_trug(trug: Any) -> Dict[str, Any]:
    """Accept dict, path, or string; return parsed TRUG dict.

    When given a path/string, loads via trugs-store and reconstructs
    the dict format that the rendering functions expect.
    """
    if isinstance(trug, dict):
        return trug
    if isinstance(trug, (str, Path)):
        path = Path(trug)
        store = JsonFilePersistence().load(str(path))
        # Reconstruct dict format for backward compatibility with render functions
        result = dict(store.get_metadata())
        result["nodes"] = store.find_nodes()
        result["edges"] = store.get_edges()
        return result
    raise TypeError(f"Expected dict, str, or Path; got {type(trug)}")


def _get_folder_node(trug: Dict[str, Any]) -> Dict[str, Any]:
    """Find the FOLDER root node."""
    for node in trug.get("nodes", []):
        if node.get("type") == "FOLDER":
            return node
    # Fallback: find any root node (parent_id is null)
    for node in trug.get("nodes", []):
        if node.get("parent_id") is None:
            return node
    raise ValueError("No FOLDER or root node found in TRUG")


def _get_children(trug: Dict[str, Any], parent_id: str) -> List[Dict[str, Any]]:
    """Get child nodes of a parent, sorted by type then name."""
    children = [n for n in trug.get("nodes", []) if n.get("parent_id") == parent_id]
    children.sort(key=lambda n: (n.get("type", ""), n.get("properties", {}).get("name", n.get("id", ""))))
    return children


def _group_by_type(nodes: List[Dict[str, Any]]) -> List[Tuple[str, List[Dict[str, Any]]]]:
    """Group nodes by type, sorted by type name."""
    groups: Dict[str, List[Dict[str, Any]]] = {}
    for node in nodes:
        t = node.get("type", "UNKNOWN")
        groups.setdefault(t, []).append(node)
    return sorted(groups.items())


def _get_edges_from(trug: Dict[str, Any], node_id: str) -> List[Dict[str, Any]]:
    """Get outbound edges from a node, sorted by relation then target."""
    edges = [e for e in trug.get("edges", []) if e.get("from_id") == node_id]
    edges.sort(key=lambda e: (e.get("relation", ""), e.get("to_id", "")))
    return edges


def _get_edges_to(trug: Dict[str, Any], node_id: str) -> List[Dict[str, Any]]:
    """Get inbound edges to a node, sorted by relation then source."""
    edges = [e for e in trug.get("edges", []) if e.get("to_id") == node_id]
    edges.sort(key=lambda e: (e.get("relation", ""), e.get("from_id", "")))
    return edges


def _node_name(node: Dict[str, Any]) -> str:
    """Get display name for a node."""
    return node.get("properties", {}).get("name", node.get("id", "unnamed"))


def _node_purpose(node: Dict[str, Any]) -> str:
    """Get purpose/description for a node."""
    return node.get("properties", {}).get("purpose", "")


def _node_map(trug: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    """Build node_id → node lookup."""
    return {n["id"]: n for n in trug.get("nodes", []) if "id" in n}


# ─── AAA.md Renderer ─────────────────────────────────────────────────


def render_aaa(trug: Any, render_date: Optional[str] = None) -> str:
    """Render AAA.md from a folder TRUG.

    Produces the 9-phase AAA.md format with header, phases, and metadata.

    Args:
        trug: TRUG dict, file path, or JSON string
        render_date: Fixed date string for deterministic output. Defaults to today.
    """
    data = _load_trug(trug)
    folder = _get_folder_node(data)
    props = folder.get("properties", {})
    children = _get_children(data, folder["id"])
    nmap = _node_map(data)

    name = props.get("name", "Unknown")
    purpose = props.get("purpose", "")
    phase = props.get("phase", "VISION")
    status = props.get("status", "ACTIVE")
    version = props.get("version", "0.1.0")
    today = render_date or date.today().isoformat()

    lines = []
    lines.append(GENERATED_HEADER)
    lines.append(f"<!-- Source: folder.trug.json | Generated: {today} -->")
    lines.append("")
    lines.append(f"# {name}/")
    lines.append("")
    lines.append(f"**Project:** {purpose}")
    lines.append(f"**Version:** {version}")
    lines.append(f"**Phase:** {phase}")
    lines.append(f"**Status:** {status}")
    lines.append(f"**Last Updated:** {today}")
    lines.append("**Parent:** [../AAA.md](../AAA.md)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # VISION
    lines.append("## VISION")
    lines.append("")
    lines.append(f"**Phase Status:** {'COMPLETE' if phase != 'VISION' else 'ACTIVE'}")
    lines.append("")
    lines.append(f"### What We're Building")
    lines.append("")
    description = data.get("description", "")
    if description:
        lines.append(description)
    else:
        lines.append(purpose)
    lines.append("")

    # Contents summary
    non_generated = [c for c in children if c.get("type") != "GENERATED"]
    if non_generated:
        lines.append("### Components")
        lines.append("")
        for group_type, group_nodes in _group_by_type(non_generated):
            for node in group_nodes:
                n_name = _node_name(node)
                n_purpose = _node_purpose(node)
                suffix = f" — {n_purpose}" if n_purpose else ""
                lines.append(f"- **{n_name}**{suffix}")
        lines.append("")

    lines.append("---")
    lines.append("")

    # FEASIBILITY through DEPLOYMENT — render as phase stubs
    for phase_name in ["FEASIBILITY", "SPECIFICATIONS", "ARCHITECTURE",
                       "CODING", "TESTING", "DEPLOYMENT"]:
        lines.append(f"## {phase_name}")
        lines.append("")
        if phase_name == "ARCHITECTURE":
            # Render the reference tree
            lines.append("**Reference Tree:**")
            lines.append("```")
            lines.append(f"{name}/")
            lines.append(f"├── folder.trug.json (source of truth)")
            for i, child in enumerate(children):
                prefix = "└──" if i == len(children) - 1 else "├──"
                c_name = _node_name(child)
                c_type = child.get("type", "")
                marker = " (generated)" if c_type == "GENERATED" else ""
                lines.append(f"{prefix} {c_name}{marker}")
            lines.append("```")
            lines.append("")

            # Render edge relationships
            all_edges = data.get("edges", [])
            if all_edges:
                lines.append("**Relationships:**")
                lines.append("")
                lines.append("| From | Relation | To | Weight | Description |")
                lines.append("|------|----------|----|--------|-------------|")
                for edge in sorted(all_edges, key=lambda e: (e.get("relation", ""), e.get("from_id", ""))):
                    from_name = _node_name(nmap.get(edge.get("from_id", ""), {}))
                    to_name = _node_name(nmap.get(edge.get("to_id", ""), {}))
                    relation = edge.get("relation", "")
                    desc = edge.get("properties", {}).get("description", "")
                    w = edge.get("weight")
                    weight_str = f"{w:.2f}" if w is not None else "—"
                    lines.append(f"| {from_name} | {relation} | {to_name} | {weight_str} | {desc} |")
                lines.append("")

                # Dependencies grouped by relation type
                dep_groups: Dict[str, List[Tuple[str, str]]] = {}
                for edge in sorted(all_edges, key=lambda e: (e.get("relation", ""), e.get("from_id", ""))):
                    rel = edge.get("relation", "")
                    from_n = _node_name(nmap.get(edge.get("from_id", ""), {}))
                    to_n = _node_name(nmap.get(edge.get("to_id", ""), {}))
                    dep_groups.setdefault(rel, []).append((from_n, to_n))
                lines.append("**Dependencies:**")
                lines.append("")
                for rel, pairs in sorted(dep_groups.items()):
                    lines.append(f"*{rel}:*")
                    for from_n, to_n in pairs:
                        lines.append(f"- {from_n} → {to_n}")
                lines.append("")
        else:
            lines.append(f"**Phase Status:** —")
            lines.append("")
        lines.append("---")
        lines.append("")

    # TASKS — list non-FOLDER, non-GENERATED nodes grouped by type
    task_nodes = [n for n in data.get("nodes", [])
                  if n.get("type") not in ("FOLDER", "GENERATED")]
    if task_nodes:
        lines.append("## TASKS")
        lines.append("")
        for group_type, group_nodes in _group_by_type(task_nodes):
            lines.append(f"### {group_type}")
            lines.append("")
            for node in group_nodes:
                n_name = _node_name(node)
                n_purpose = _node_purpose(node)
                n_level = node.get("metric_level", "")
                detail = f" — {n_purpose}" if n_purpose else ""
                level_tag = f" `{n_level}`" if n_level else ""
                lines.append(f"- **{n_name}**{detail}{level_tag}")
            lines.append("")
        lines.append("---")
        lines.append("")

    # METADATA
    lines.append("## METADATA")
    lines.append("")
    lines.append("```json")
    meta = {
        "source": "folder.trug.json",
        "trug_name": data.get("name", ""),
        "trug_version": data.get("version", ""),
        "trug_type": data.get("type", ""),
        "nodes": len(data.get("nodes", [])),
        "edges": len(data.get("edges", [])),
    }
    lines.append(json.dumps(meta, indent=2))
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


# ─── README.md Renderer ──────────────────────────────────────────────


def render_readme(trug: Any, render_date: Optional[str] = None) -> str:
    """Render README.md from a folder TRUG.

    Produces a human-friendly orientation document.

    Args:
        trug: TRUG dict, file path, or JSON string
        render_date: Fixed date string for deterministic output. Defaults to today.
    """
    data = _load_trug(trug)
    folder = _get_folder_node(data)
    props = folder.get("properties", {})
    children = _get_children(data, folder["id"])
    nmap = _node_map(data)

    name = props.get("name", "Unknown")
    purpose = props.get("purpose", "")
    version = props.get("version", "")
    status = props.get("status", "")
    today = render_date or date.today().isoformat()

    lines = []
    lines.append(GENERATED_HEADER)
    lines.append(f"<!-- Source: folder.trug.json | Generated: {today} -->")
    lines.append("")
    lines.append(f"# {name}")
    lines.append("")
    lines.append(f"> **For System Architecture:** See [ARCHITECTURE.md](ARCHITECTURE.md)")
    lines.append(f"> **For Development Status:** See [AAA.md](AAA.md)")
    lines.append("")
    if purpose:
        lines.append(f"**{purpose}**")
        lines.append("")
    if version or status:
        parts = []
        if version:
            parts.append(f"**Version:** {version}")
        if status:
            parts.append(f"**Status:** {status}")
        lines.append(" | ".join(parts))
        lines.append("")

    lines.append("---")
    lines.append("")

    # Contents section
    non_generated = [c for c in children if c.get("type") != "GENERATED"]
    if non_generated:
        lines.append("## Contents")
        lines.append("")
        lines.append("| File | Type | Purpose |")
        lines.append("|------|------|---------|")
        for node in non_generated:
            n_name = _node_name(node)
            n_type = node.get("type", "")
            n_purpose = _node_purpose(node)
            fmt = node.get("properties", {}).get("format", "")
            # Link markdown files
            if fmt == "markdown" or n_name.endswith(".md"):
                n_name = f"[{n_name}]({n_name})"
            lines.append(f"| {n_name} | {n_type} | {n_purpose} |")
        lines.append("")

    # Getting Started section
    description = data.get("description", "")
    md_files = [_node_name(c) for c in non_generated
                if c.get("properties", {}).get("format", "") == "markdown"
                or _node_name(c).endswith(".md")] if non_generated else []
    if description or version or md_files:
        lines.append("## Getting Started")
        lines.append("")
        if description:
            lines.append(description)
            lines.append("")
        if version:
            lines.append(f"**Current Version:** {version}")
            lines.append("")
        if md_files:
            lines.append("**Key Documents:**")
            for md in sorted(md_files):
                lines.append(f"- [{md}]({md})")
            lines.append("")

    # Relationships section (only interesting cross-references)
    all_edges = data.get("edges", [])
    if all_edges:
        lines.append("## How It Fits Together")
        lines.append("")
        for edge in sorted(all_edges, key=lambda e: (e.get("relation", ""), e.get("from_id", ""))):
            from_name = _node_name(nmap.get(edge.get("from_id", ""), {}))
            to_name = _node_name(nmap.get(edge.get("to_id", ""), {}))
            relation = edge.get("relation", "").replace("_", " ").lower()
            desc = edge.get("properties", {}).get("description", "")
            w = edge.get("weight")
            weight_str = f" ({w:.2f})" if w is not None else ""
            if desc:
                lines.append(f"- **{from_name}** {relation}{weight_str} **{to_name}** — {desc}")
            else:
                lines.append(f"- **{from_name}** {relation}{weight_str} **{to_name}**")
        lines.append("")

    # Dependencies section (IMPLEMENTS, REFERENCES, EXTENDS edges)
    dep_relations = {"IMPLEMENTS", "REFERENCES", "EXTENDS"}
    dep_edges = [e for e in data.get("edges", []) if e.get("relation", "") in dep_relations]
    if dep_edges:
        lines.append("## Dependencies")
        lines.append("")
        for edge in sorted(dep_edges, key=lambda e: (e.get("relation", ""), e.get("from_id", ""))):
            from_name = _node_name(nmap.get(edge.get("from_id", ""), {}))
            to_name = _node_name(nmap.get(edge.get("to_id", ""), {}))
            relation = edge.get("relation", "").replace("_", " ").lower()
            lines.append(f"- **{from_name}** {relation} **{to_name}**")
        lines.append("")

    # Documentation links
    lines.append("## Documentation")
    lines.append("")
    lines.append("- [AAA.md](AAA.md) — Development tracking and task status")
    lines.append("- [ARCHITECTURE.md](ARCHITECTURE.md) — Technical reference")
    lines.append("- [../AAA.md](../AAA.md) — Parent project")
    lines.append("")

    return "\n".join(lines)


# ─── ARCHITECTURE.md Renderer ────────────────────────────────────────


def _get_prose_content(data: Dict[str, Any], zone: str, repo_root: Optional[Path]) -> str:
    """Return prose file content for a zone, or empty string."""
    if repo_root is None:
        return ""

    prose_nodes = [
        n for n in data.get("nodes", [])
        if n.get("type") == "PROSE"
        and n.get("properties", {}).get("zone") == zone
    ]
    if not prose_nodes:
        return ""

    file_rel = prose_nodes[0].get("properties", {}).get("file", "")
    if not file_rel:
        return ""

    prose_path = repo_root / file_rel
    if not prose_path.exists():
        warnings.warn(f"PROSE file not found: {prose_path} (zone={zone})")
        return ""

    return prose_path.read_text(encoding="utf-8").strip()


def render_architecture(
        trug: Any,
        render_date: Optional[str] = None,
        repo_root: Optional[Union[str, Path]] = None) -> str:
    """Render ARCHITECTURE.md from a folder TRUG.

    Produces a dense technical reference document for LLMs and architects.

    Args:
        trug: TRUG dict, file path, or JSON string
        render_date: Fixed date string for deterministic output. Defaults to today.
        repo_root: Optional repository root used to load PROSE zone files.
    """
    data = _load_trug(trug)
    root_path = Path(repo_root) if repo_root is not None else None
    folder = _get_folder_node(data)
    props = folder.get("properties", {})
    children = _get_children(data, folder["id"])
    nmap = _node_map(data)

    name = props.get("name", "Unknown")
    purpose = props.get("purpose", "")
    version = props.get("version", "")
    status = props.get("status", "")
    phase = props.get("phase", "")
    today = render_date or date.today().isoformat()

    lines: List[str] = []

    # S-01: Generated Header
    lines.append(GENERATED_HEADER)
    lines.append(f"<!-- Source: folder.trug.json | Generated: {today} -->")
    lines.append("")
    lines.append(f"# {name} Architecture")
    lines.append("")
    lines.append(f"> **For Development Context:** See [AAA.md](AAA.md)")
    lines.append(f"> **For Human-Friendly Docs:** See [README.md](README.md)")
    lines.append("")

    # S-02: Trust Notices for DOCUMENT nodes
    doc_nodes = sorted(
        [n for n in data.get("nodes", []) if n.get("type") == "DOCUMENT"],
        key=lambda n: (n.get("type", ""), n.get("id", "")),
    )
    trust_notices: List[str] = []
    for node in doc_nodes:
        node_props = node.get("properties", {})
        node_name = node_props.get("name", node.get("id", "unnamed"))
        is_stale = node_props.get("stale", False)
        is_verified = node_props.get("verified", False)
        if is_verified and is_stale:
            # CONFLICT: human verified but drift detected
            stale_reason = node_props.get("stale_reason", "")
            last_verified = node_props.get("last_verified", "unknown")
            trug_hash = node_props.get("trug_hash", "unknown")
            reason_str = f" {stale_reason}" if stale_reason else ""
            trust_notices.append(
                f"> 🚨 CONFLICT: {node_name} was verified but drift detected.{reason_str}\n"
                f"> Last verified: {last_verified} | TRUG: {trug_hash}\n"
                f"> Human action required. Re-verify {node_name}."
            )
        elif is_stale:
            stale_reason = node_props.get("stale_reason", "")
            last_verified = node_props.get("last_verified", "unknown")
            trug_hash = node_props.get("trug_hash", "unknown")
            reason_str = f" {stale_reason}" if stale_reason else ""
            trust_notices.append(
                f"> ⚠️ STALE: {node_name}{reason_str}\n"
                f"> Last verified: {last_verified} | TRUG: {trug_hash}\n"
                f"> Human action required. Do not use {node_name} as authoritative context."
            )
        elif is_verified:
            verified_by = node_props.get("verified_by", "unknown")
            verified_date = node_props.get("verified_date", "unknown")
            trug_hash = node_props.get("trug_hash", "unknown")
            trust_notices.append(
                f"> ✅ VERIFIED: {node_name} confirmed current by {verified_by} on {verified_date} (TRUG: {trug_hash})"
            )
    if trust_notices:
        for notice in trust_notices:
            lines.append(notice)
            lines.append("")

    # S-03: Quick Reference (phase, status, version)
    lines.append(f"**Version:** {version}")
    lines.append(f"**Purpose:** {purpose}")
    lines.append(f"**Phase:** {phase}")
    lines.append(f"**Status:** {status}")
    lines.append(f"**Source:** `folder.trug.json`")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Quick Reference")
    lines.append("")
    lines.append(f"**What:** {purpose}")
    lines.append(f"**Type:** {data.get('type', 'PROJECT')}")
    lines.append(f"**Nodes:** {len(data.get('nodes', []))}")
    lines.append(f"**Edges:** {len(data.get('edges', []))}")

    # Component statistics by type
    type_counts: Dict[str, int] = {}
    for node in data.get("nodes", []):
        ntype = node.get("type", "UNKNOWN")
        type_counts[ntype] = type_counts.get(ntype, 0) + 1
    if type_counts:
        stats = ", ".join(f"{t}: {c}" for t, c in sorted(type_counts.items()))
        lines.append(f"**Components:** {stats}")
    lines.append("")

    # Dimensions
    dims = data.get("dimensions", {})
    if dims:
        lines.append("**Dimensions:**")
        for dim_name, dim_info in sorted(dims.items()):
            desc = dim_info.get("description", "")
            lines.append(f"- `{dim_name}`: {desc}")
        lines.append("")

    # Capabilities
    caps = data.get("capabilities", {})
    if caps:
        exts = caps.get("extensions", [])
        vocabs = caps.get("vocabularies", [])
        if exts or vocabs:
            lines.append("**Capabilities:**")
            if vocabs:
                lines.append(f"- Vocabularies: {', '.join(vocabs)}")
            if exts:
                lines.append(f"- Extensions: {', '.join(exts)}")
            lines.append("")

    lines.append("---")
    lines.append("")
    prose = _get_prose_content(data, "overview", root_path)
    lines.append("<!-- WRITER:BEGIN overview -->")
    if prose:
        lines.append(prose)
    lines.append("<!-- WRITER:END overview -->")
    lines.append("")

    # S-04: Component Inventory
    lines.append("## Component Inventory")
    lines.append("")
    lines.append("| Type | Name | Purpose |")
    lines.append("|------|------|---------|")
    for node in sorted(data.get("nodes", []),
                       key=lambda n: (n.get("type", ""), n.get("id", ""))):
        ntype = node.get("type", "")
        nname = _node_name(node)
        npurpose = _node_purpose(node)
        lines.append(f"| {ntype} | {nname} | {npurpose} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    prose = _get_prose_content(data, "component_notes", root_path)
    lines.append("<!-- WRITER:BEGIN component_notes -->")
    if prose:
        lines.append(prose)
    lines.append("<!-- WRITER:END component_notes -->")
    lines.append("")

    # S-05: Component Hierarchy Tree
    lines.append("## Component Hierarchy")
    lines.append("")
    lines.append("```")
    lines.append(f"{name}/ (FOLDER, {folder.get('metric_level', '')})")
    for i, child in enumerate(children):
        prefix = "└── " if i == len(children) - 1 else "├── "
        c_name = _node_name(child)
        c_type = child.get("type", "")
        c_level = child.get("metric_level", "")
        lines.append(f"  {prefix}{c_name} ({c_type}, {c_level})")
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")
    prose = _get_prose_content(data, "hierarchy_notes", root_path)
    lines.append("<!-- WRITER:BEGIN hierarchy_notes -->")
    if prose:
        lines.append(prose)
    lines.append("<!-- WRITER:END hierarchy_notes -->")
    lines.append("")

    # S-06: Node Detail Table
    lines.append("## Node Details")
    lines.append("")
    lines.append("| ID | Type | Name | Metric Level | Purpose |")
    lines.append("|----|------|------|-------------|---------|")
    all_nodes = sorted(data.get("nodes", []),
                       key=lambda n: (n.get("type", ""), n.get("id", "")))
    for node in all_nodes:
        nid = node.get("id", "")
        ntype = node.get("type", "")
        nname = _node_name(node)
        nlevel = node.get("metric_level", "")
        npurpose = _node_purpose(node)
        lines.append(f"| `{nid}` | {ntype} | {nname} | {nlevel} | {npurpose} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Separate internal and cross-folder edges
    all_edges = data.get("edges", [])
    internal_edges = [e for e in all_edges if ":" not in str(e.get("to_id", ""))]
    cross_folder_edges = [e for e in all_edges if ":" in str(e.get("to_id", ""))]

    # S-07: Cross-Folder Dependencies
    if cross_folder_edges:
        lines.append("## Cross-Folder Dependencies")
        lines.append("")
        lines.append("| From | Relation | Target Folder | Target Node | Weight |")
        lines.append("|------|----------|---------------|-------------|--------|")
        for edge in sorted(cross_folder_edges,
                           key=lambda e: (e.get("relation", ""), e.get("from_id", ""), e.get("to_id", ""))):
            from_name = _node_name(nmap.get(edge.get("from_id", ""), {}))
            to_id = str(edge.get("to_id", ""))
            parts = to_id.split(":", 1)
            target_folder = parts[0] if len(parts) == 2 else ""
            target_node = parts[1] if len(parts) == 2 else to_id
            relation = edge.get("relation", "")
            w = edge.get("weight")
            weight_str = f"{w:.2f}" if w is not None else "—"
            lines.append(f"| {from_name} | {relation} | {target_folder} | {target_node} | {weight_str} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    prose = _get_prose_content(data, "dependency_notes", root_path)
    lines.append("<!-- WRITER:BEGIN dependency_notes -->")
    if prose:
        lines.append(prose)
    lines.append("<!-- WRITER:END dependency_notes -->")
    lines.append("")

    # S-08: Internal Relationships
    if internal_edges:
        lines.append("## Relationships")
        lines.append("")
        lines.append("| From | Relation | To | Weight | Description |")
        lines.append("|------|----------|----|--------|-------------|")
        for edge in sorted(internal_edges,
                           key=lambda e: (e.get("relation", ""), e.get("from_id", ""), e.get("to_id", ""))):
            from_name = _node_name(nmap.get(edge.get("from_id", ""), {}))
            to_name = _node_name(nmap.get(edge.get("to_id", ""), {}))
            relation = edge.get("relation", "")
            desc = edge.get("properties", {}).get("description", "")
            w = edge.get("weight")
            weight_str = f"{w:.2f}" if w is not None else "—"
            lines.append(f"| {from_name} | {relation} | {to_name} | {weight_str} | {desc} |")
        lines.append("")

    # S-09: Dependency Graph (all edges)
    if all_edges:
        lines.append("## Dependency Graph")
        lines.append("")
        lines.append("```")
        for edge in sorted(all_edges,
                           key=lambda e: (e.get("relation", ""), e.get("from_id", ""), e.get("to_id", ""))):
            from_name = _node_name(nmap.get(edge.get("from_id", ""), {}))
            to_id = edge.get("to_id", "")
            if ":" in str(to_id):
                to_name = str(to_id)
            else:
                to_name = _node_name(nmap.get(to_id, {}))
            relation = edge.get("relation", "")
            w = edge.get("weight")
            if w is not None:
                lines.append(f"{from_name} --[{relation}, {w:.2f}]--> {to_name}")
            else:
                lines.append(f"{from_name} --[{relation}]--> {to_name}")
        lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("")

    # S-10: Test Summary (from TEST_SUITE nodes)
    test_nodes = sorted(
        [n for n in data.get("nodes", []) if n.get("type") == "TEST_SUITE"],
        key=lambda n: (n.get("type", ""), n.get("id", "")),
    )
    if test_nodes:
        lines.append("## Test Summary")
        lines.append("")
        lines.append("| Test Suite | Test Count | Coverage | Test Files |")
        lines.append("|------------|-----------|----------|------------|")
        for node in test_nodes:
            node_props = node.get("properties", {})
            suite_name = node_props.get("name", node.get("id", "unnamed"))
            test_count = node_props.get("test_count", "—")
            coverage = node_props.get("coverage", "—")
            test_files = node_props.get("test_files", "—")
            lines.append(f"| {suite_name} | {test_count} | {coverage} | {test_files} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    # S-11: File Statistics (from node properties with file_count, loc)
    file_stat_nodes = sorted(
        [n for n in data.get("nodes", [])
         if any(k in n.get("properties", {}) for k in ("file_count", "loc", "files"))],
        key=lambda n: (n.get("type", ""), n.get("id", "")),
    )
    if file_stat_nodes:
        lines.append("## File Statistics")
        lines.append("")
        lines.append("| Component | File Count | LOC |")
        lines.append("|-----------|-----------|-----|")
        for node in file_stat_nodes:
            node_props = node.get("properties", {})
            comp_name = node_props.get("name", node.get("id", "unnamed"))
            file_count = node_props.get("file_count", "")
            if not file_count:
                files = node_props.get("files", [])
                if isinstance(files, list):
                    file_count = str(len(files))
            loc = node_props.get("loc", "—")
            lines.append(f"| {comp_name} | {file_count} | {loc} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Specification Links (from SPECIFICATION nodes)
    spec_nodes = sorted(
        [n for n in data.get("nodes", []) if n.get("type") == "SPECIFICATION"],
        key=lambda n: (n.get("type", ""), n.get("id", "")),
    )
    if spec_nodes:
        lines.append("## Specifications")
        lines.append("")
        for node in spec_nodes:
            node_props = node.get("properties", {})
            spec_name = node_props.get("name", node.get("id", "unnamed"))
            spec_purpose = node_props.get("purpose", "")
            fmt = node_props.get("format", "")
            if fmt == "markdown" or spec_name.endswith(".md"):
                lines.append(f"- [{spec_name}]({spec_name}) — {spec_purpose}")
            else:
                lines.append(f"- **{spec_name}** — {spec_purpose}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Example Links (from EXAMPLE_SET nodes)
    example_nodes = sorted(
        [n for n in data.get("nodes", []) if n.get("type") == "EXAMPLE_SET"],
        key=lambda n: (n.get("type", ""), n.get("id", "")),
    )
    if example_nodes:
        lines.append("## Examples")
        lines.append("")
        for node in example_nodes:
            node_props = node.get("properties", {})
            ex_name = node_props.get("name", node.get("id", "unnamed"))
            ex_purpose = node_props.get("purpose", "")
            ex_count = node_props.get("example_count", "")
            count_str = f" ({ex_count} examples)" if ex_count else ""
            lines.append(f"- **{ex_name}**{count_str} — {ex_purpose}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # S-12: Node Properties (detailed)
    lines.append("## Node Properties")
    lines.append("")
    for node in all_nodes:
        nname = _node_name(node)
        ntype = node.get("type", "")
        node_props = node.get("properties", {})
        lines.append(f"### {nname} ({ntype})")
        lines.append("")
        if node_props:
            for k, v in sorted(node_props.items()):
                lines.append(f"- **{k}:** {v}")
        else:
            lines.append("*No properties*")
        lines.append("")

    return "\n".join(lines)


# ─── Batch Renderer ──────────────────────────────────────────────────


def render_all(
        trug: Any,
        output_dir: Optional[str] = None,
        render_date: Optional[str] = None,
        repo_root: Optional[Union[str, Path]] = None) -> Dict[str, str]:
    """Render all three markdown files from a TRUG.

    Args:
        trug: TRUG dict, file path, or JSON string
        output_dir: Directory to write files. If None, returns content only.
        render_date: Fixed date string for deterministic output. Defaults to today.
        repo_root: Optional repository root used to load PROSE zone files.

    Returns:
        Dict mapping filename → rendered content
    """
    results = {
        "AAA.md": render_aaa(trug, render_date=render_date),
        "README.md": render_readme(trug, render_date=render_date),
        "ARCHITECTURE.md": render_architecture(trug, render_date=render_date, repo_root=repo_root),
    }

    if output_dir:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        for filename, content in results.items():
            (out / filename).write_text(content, encoding="utf-8")

    return results
